import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import { getServerSession } from 'next-auth';
const outfit = Outfit({ subsets: ['latin'], variable: '--font-sans' });

// Components
import Nav from '@/lib/components/misc/Nav/Nav';

// Providers
import SessionProvider from '@/providers/SessionProvider';
import ThemeProvider from '@/providers/ThemeProvider';

// Styles
import './globals.scss';

// Utils
import { cn } from '@/lib/utils';
import { createClient } from '@/lib/supabase/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const session = await getServerSession();
  const supabase = createClient();

  const { data } = await supabase.auth.getSession();

  // console.log('supabase data', data);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          outfit.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            {/* {session?.user && <Nav />} */}
            <Nav session={data.session} />
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
