import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import { getServerSession } from 'next-auth';
const outfit = Outfit({ subsets: ['latin'], variable: '--font-sans' });

// Components
import Nav from '@/components/Nav/Nav';

// Providers
import SessionProvider from '@/providers/SessionProvider';

// Styles
import './globals.scss';

// Utils
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const session = await getServerSession();

  return (
    <html lang={locale}>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          outfit.variable
        )}
      >
        <SessionProvider session={session}>
          {session?.user && <Nav />}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
